import { DEFAULT_PAGINATION_LIMIT, MAX_PAGINATION_LIMIT } from '../common/pagination/limits';

export const DEFAULT_EMPLOYEES_PER_PAGE = DEFAULT_PAGINATION_LIMIT;

export const MAX_EMPLOYEES_PER_PAGE = MAX_PAGINATION_LIMIT;
